# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "kali"
  config.vm.box_url="http://ftp.sliim-projects.eu/boxes/kali-linux-1.0-amd64.box"
  config.vm.network "public_network", ip: "192.168.0.17"
  config.ssh.forward_agent = true
  config.ssh.username = "root"
  config.ssh.password = "toor"
end
